Django/Webbramverk/AMPTA/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.models import User, Group
from django.views.generic import DetailView, ListView
from AMPTA.models import Project, Ticket, Status

from AMPTA import views

urlpatterns = patterns("", 
	url(r'^$', views.index, name = "index"),
	url(r'^login', views.login_user, name = "login"),
	url(r'^logout$', views.logout_user, name = "logout"),
	# project
	url(r'^projects/$', views.projects, name = "projects" ),
	url(r'^projects/(?P<project_id>\d+)$', views.show_project, name = "show_project" ),
	url(r'^projects/(?P<project_id>\d+)/edit$', views.edit_project, name = "edit_project" ),
	url(r'^projects/new$', views.new_project, name = "new_project" ),
	url(r'^projects/create$', views.create_project, name = "create_project" ),
	url(r'^projects/(?P<project_id>\d+)/delete$', views.delete_project, name = "delete_project" ),
	# ticket
	url(r'^projects/(?P<project_id>\d+)/tickets/(?P<ticket_id>\d+)$', views.show_ticket, name = "show_ticket" ),
	url(r'^projects/(?P<project_id>\d+)/tickets/(?P<ticket_id>\d+)/edit$', views.edit_ticket, name = "edit_ticket" ),
	url(r'^projects/(?P<project_id>\d+)/tickets/new$', views.new_ticket, name = "new_ticket" ),
	url(r'^projects/(?P<project_id>\d+)/tickets/create$', views.create_ticket, name = "create_ticket" ),
	url(r'^projects/(?P<project_id>\d+)/tickets/(?P<ticket_id>\d+)/delete$', views.delete_ticket, name = "delete_ticket" ),
	# user
	url(r'^users/$', views.users, name = "users" ),
	url(r'^users/(?P<user_id>\d+)$', views.show_user, name = "show_user" ),
	url(r'^users/(?P<user_id>\d+)/edit$', views.edit_user, name = "edit_user" ),
)

Django/Webbramverk/Webbramverk/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
# from AMPTA.models import Project, Ticket, Status
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Webbramverk.views.home', name='home'),
    # url(r'^Webbramverk/', include('Webbramverk.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^ampta/admin/', include(admin.site.urls)),
    url(r'^ampta/', include("AMPTA.urls", namespace = "AMPTA")),
)

Django/Webbramverk/AMPTA/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User, Group
from django.core.exceptions import ValidationError
from django.utils import timezone
import datetime
from django.forms import ModelForm, Widget
from django import forms

# Create your models here.
class Project(models.Model):
	"""docstring for Project"""
	members = models.ManyToManyField(User, related_name = "projects", error_messages = { "required": "hello" })
	name = models.CharField(max_length = 50, blank = False)
	description = models.TextField(blank = False)
	start_date = models.DateTimeField("Startdatum för projektet")
	end_date = models.DateTimeField("Slutdatum för projektet")
	owner = models.ForeignKey(User, related_name = "owner")
	def __unicode__(self):
		return self.name
	def is_member(self, user):
		return self.members.filter(pk = user.id)
	def valid_deadline(self):
		return self.start_date < self.end_date

class Status(models.Model):
	"""docstring for Status"""
	status_name = models.CharField(max_length = 50, blank = False)
	def __unicode__(self):
		return self.status_name

class Ticket(models.Model):
	"""docstring for Ticket"""
	name = models.CharField(max_length = 50, blank = False)
	description = models.TextField(blank = False)
	project = models.ForeignKey(Project)
	status = models.ForeignKey(Status)
	owner = models.ForeignKey(User, related_name = "tickets")
	def __unicode__(self):
		return self.name

class LoginForm(forms.Form):
	"""docstring for LoginForm"""
	username = forms.CharField(max_length = 30, widget = forms.TextInput(attrs = { "class": "input-block-level" }))
	password = forms.CharField(max_length = 30, widget = forms.PasswordInput(attrs = { "class": "input-block-level" }))

class TicketForm(ModelForm):
	"""docstring for ClassName"""
	class Meta:
		model = Ticket
		exclude = ("project"), ("owner")

class ProjectForm(ModelForm):
	"""docstring for ProjectForm"""
	name = forms.CharField(widget = forms.TextInput(attrs = { "class": "input-xlarge" }))
	description = forms.CharField(widget = forms.Textarea(attrs = { "class": "input-xlarge" }))
	start_date = forms.DateField(initial = timezone.now(), widget = forms.DateInput(attrs = { "class": "span12", "readonly": "" }))
	end_date = forms.DateField(initial = timezone.now() + datetime.timedelta(days = 5), widget = forms.DateInput(attrs = { "class": "span12", "readonly": "" }))
	class Meta:
		model = Project
		exclude = ("owner")
	def clean(self):
		cleaned_data = super(ProjectForm, self).clean()
		start_date = cleaned_data["start_date"]
		end_date = cleaned_data["end_date"]
		if start_date > end_date:
			raise forms.ValidationError("Datum för deadline måste ligga efter startdatum")
		return cleaned_data

class UserForm(ModelForm):
	first_name = forms.CharField(widget = forms.TextInput(attrs = { "class": "input-xlarge", "placeholder": "Förnamn" }))
	last_name = forms.CharField(widget = forms.TextInput(attrs = { "class": "input-xlarge", "placeholder": "Efternamn" }))
	email = forms.EmailField(widget = forms.TextInput(attrs = { "class": "input-xlarge", "placeholder": "Epost" }))
	class Meta:
		model = User
		exclude = ("id"), ("password"), ("last_login"), ("is_superuser"), ("username"), ("is_staff"), ("is_active"), ("date_joined")
			
		














		

Django/Webbramverk/AMPTA/views.py
# -*- coding: utf-8 -*-

# Create your views here.
from django.shortcuts import get_list_or_404, get_object_or_404, render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User, Group

from django.contrib.auth.decorators import login_required, permission_required

from django import template
from django.http import HttpResponse
from django.template import Context, loader
from django.forms import forms

from django.core.urlresolvers import reverse

from AMPTA.models import Project, Ticket, Status, LoginForm, TicketForm, ProjectForm, UserForm

@login_required
def index(request):
	page = "index"
	context = { "page": page }
	return render(request, "index.html", context)

def login_user(request):
	if request.user.is_authenticated():
		return redirect("AMPTA:index")
	message = ""

	if request.method == "POST":
		form = LoginForm(request.POST)
		if form.is_valid():
			username_to_try = form.cleaned_data["username"]
			password_to_try = form.cleaned_data["password"]

			user = authenticate(username = username_to_try, password = password_to_try)
			if user is not None:
				if user.is_active:
					login(request, user)
					return redirect("AMPTA:index")
				else:
					return HttpResponse("<h1>Konto inaktiverat</h1>")	
			else:
				message = "Fel användarnamn eller lösenord"
	else:
		form = LoginForm()
	return render(request, "login/index.html", { "form": form, "message": message })

@login_required
def logout_user(request):
	logout(request)
	return redirect("AMPTA:login")

@login_required
def projects(request):
	projects = get_list_or_404(Project)
	page = "projects"
	context = { "projects": projects, "page": page }
	return render(request, "projects/index.html", context)

@login_required
def show_project(request, project_id):
	project = get_object_or_404(Project, pk = project_id)
	tickets = Ticket.objects.filter(project = project)
	page = "projects"
	context = { "project": project, "tickets": tickets, "page": page }
	return render(request, "projects/show.html", context)

@login_required
def edit_project(request, project_id):
	project = get_object_or_404(Project, pk = project_id)
	page = "projects"
	if request.user.id is not project.owner.id:
		return redirect("AMPTA:show_project", str(project_id))
	if request.method == "POST":
		form = ProjectForm(request.POST, instance = project)
		if form.is_valid():
			project = form.save(commit = False)
			if request.user not in project.members.all():
				project.members.add(request.user)
			project.save()
			context = { "project": project }
			return redirect("AMPTA:show_project", str(project_id))
		else:
			message = "Felaktig formulärdata"
			return render(request, "projects/edit.html", { "project": project, "form": form, "message": message, "page": page })
	if project is not None:
		form = ProjectForm(instance = project)
		context = { "project": project, "form": form }
		return render(request, "projects/edit.html", context)
	else:
		return render(request, "index.html")

@login_required
def new_project(request):
	form = ProjectForm()
	page = "new_project"
	context = { "form": form, "page": page }
	return render(request, "projects/new.html", context)

@login_required
def create_project(request):
	page = "new_project"
	if request.method == "POST":
		form = ProjectForm(request.POST)
		if form.is_valid():
			form.instance.owner = request.user
			project = form.save();
			context = { "project_id": project.id }
			return redirect("AMPTA:show_project", str(project.id))
		else:
			message = "Felaktig formulärdata"
			return render(request, "projects/new.html", { "form": form, "message": message, "page": page })
	else:
		return redirect("AMPTA:new_project")

@login_required
def delete_project(request, project_id):
	project = get_object_or_404(Project, pk = project_id)
	if project is not None:
		if request.user.id == project.owner.id:
			project.delete();
		else:
			pass
	return redirect("AMPTA:index")

@login_required
def show_ticket(request, project_id, ticket_id):
	ticket = get_object_or_404(Ticket, pk = ticket_id)
	page = "projects"
	context = { "ticket": ticket, "page": page }
	return render(request, "tickets/show.html", context)

@login_required
def edit_ticket(request, project_id, ticket_id):
	ticket = get_object_or_404(Ticket, pk = ticket_id)
	project = get_object_or_404(Project, pk = project_id)
	page = "projects"
	if request.user.id is not project.owner.id:
		if request.user.id is not ticket.owner.id:
			return redirect("AMPTA:show_ticket", str(project_id), str(ticket_id))

	if request.method == "POST":
		form = TicketForm(request.POST, instance = ticket)
		if form.is_valid():
			ticket = form.save()
			context = { "project_id": project_id, "ticket": ticket }
			return redirect("AMPTA:show_ticket", str(project_id), str(ticket_id))
		else:
			message = "Felaktig formulärdata"
			return render(request, "tickets/edit.html", { "project": project, "ticket": ticket , "form": form, "message": message, "page": page })
	if ticket is not None and project is not None:
		form = TicketForm(instance = ticket)
		context = { "project": project, "ticket": ticket, "form": form, "page": page }
		return render(request, "tickets/edit.html", context)
	elif project is not None:
		return render(request, "project/show.html", { "project": project, "page": page })
	else:
		return render(request, "index.html", { "page": page })

@login_required
def new_ticket(request, project_id):
	project = get_object_or_404(Project, pk = project_id)
	page = "projects"
	if request.user in project.members.all():
		form = TicketForm()
		context = { "project": project, "form": form, "page": page }
		return render(request, "tickets/new.html", context)
	else:
		return redirect("AMPTA:show_project", str(project_id))

@login_required
def create_ticket(request, project_id):
	project = get_object_or_404(Project, pk = project_id)
	page = "projects"
	if request.user not in project.members.all():
		return redirect("AMPTA:show_project", str(project_id))
	if request.method == "POST":
		form = TicketForm(request.POST)
		if form.is_valid():
			form.instance.owner = request.user
			form.instance.project = project
			ticket = form.save();
			context = { "project_id": project.id, "ticket": ticket }
			return redirect("AMPTA:show_ticket", str(project_id), str(ticket.id))
		else:
			message = "Felaktig formulärdata"
			return render(request, "tickets/new.html", { "project": project, "form": form, "message": message, "page": page })
	else:
		form = TicketForm()
		context = { "project": project, "form": form, "page": page }
		return render(request, "tickets/new.html", context)

@login_required
def delete_ticket(request, project_id, ticket_id):
	project = get_object_or_404(Project, pk = project_id)
	ticket = get_object_or_404(Ticket, pk = ticket_id)
	if request.user.id is not project.owner.id:
		if request.user.id is not ticket.owner.id:
			return redirect("AMPTA:show_ticket", str(project_id), str(ticket_id))

	if project is not None:
		if ticket is not None:
			if request.user.id == ticket.owner.id:
				ticket.delete();
			elif request.user.id == project.owner.id:
				ticket.delete();
			else:
				pass
	return redirect("AMPTA:show_project", str(project_id))

@login_required
def users(request):
	inspect_users = get_list_or_404(User);
	context = { "inspect_users": inspect_users }
	return render(request, "user/index.html", context)

@login_required
def show_user(request, user_id):
	inspect_user = User.objects.get(pk = user_id)
	context = { "inspect_user": inspect_user }
	return render(request, "user/show.html", context)

@login_required
def edit_user(request, user_id):
	inspect_user = get_object_or_404(User, pk = user_id)
	
	if request.user.id is not inspect_user.id:
		if request.user.is_superuser is not True:
			return redirect("AMPTA:index")

	if inspect_user is not None:
		if request.method == "POST":
			form = UserForm(request.POST, instance = inspect_user)
			if form.is_valid():
				inspect_user = form.save()
				context = { "inspect_user": inspect_user }
				return redirect("AMPTA:show_user", str(inspect_user.id))
			else:
				message = "Felaktig formulärdata"
				return render(request, "user/edit.html", { "inspect_user": inspect_user, "form": form })
		else:
			form = UserForm(instance = inspect_user)
			context = { "inspect_user": inspect_user, "form": form }
			return render(request, "user/edit.html", context)
	else:
		return redirect("AMPTA:index")

Django/Webbramverk/AMPTA/templates/shared/base.html
<!DOCTYPE html>
<html>
<head>
  <title>Ampta</title>
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/bootstrap-responsive.css">
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/bootstrap.css">
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/datepicker.css">
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/style.css">
  <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap-datepicker.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}js/script.js"></script>
</head>
<body>
	{% if user.is_authenticated %}
		{% include "shared/menu.html" %}
	{% endif %}
	<div class="container" id="main_container">
		{% block main_content %}
			
		{% endblock %}
	</div>
</body>
</html>

Django/Webbramverk/AMPTA/templates/shared/error_messages.html
{% if form.errors %}
	<div id="error_explanation" class="alert alert-error">
		<h4>{{ form.errors.items|length }} fel i formuläret</h4>
		{% for key, value in form.errors.items %}
			<span>
				{{ value.as_text }}<br/>
			</span>
		{% endfor %}
	</div>
{% endif %}

Django/Webbramverk/AMPTA/templates/shared/menu.html
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a href="#" class="brand">AMPTA</a>
			<div class="nav-collapse collapse">
				<ul class="nav pull-left">
					<li {% if page = "index" %} class="active" {% endif %}>
						<a href="{% url 'AMPTA:index' %}">Start</a>
					</li>

					<li {% if page = "projects" %} class="active" {% endif %}>
						<a href="{% url 'AMPTA:projects' %}">All projekt</a>
					</li>

					<li {% if page = "new_project" %} class="active" {% endif %}>
						<a href="{% url 'AMPTA:new_project' %}">Skapa projekt</a>
					</li>
				</ul>
				<div class="btn-group pull-right">
					<a class="btn btn-primary" href="{% url 'AMPTA:show_user' user.id %}"><i class="icon-user icon-white"></i> {{ user.username }}</a>
					<a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a href="{% url 'AMPTA:edit_user' user.id %}"><i class="icon-pencil"></i> Redigera</a></li>
						<li class="divider"></li>
						<li><a href="{% url 'AMPTA:users' %}"> Användare</a></li>
						{% if user.is_superuser %}
							<li><a href="{% url 'admin:index' %}"> Administration</a></li>
						{% endif %}
						<li><a href="{% url 'AMPTA:logout' %}"><i class="i"></i> Logga ut</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>

Django/Webbramverk/AMPTA/templates/shared/project_form.html
<div class="control-group">
	<label class="control-label">Namn</label>
	<div class="controls">
		{{ form.name }}
	</div>
</div>

<div class="control-group">
	<label class="control-label">Beskrivning</label>
	<div class="controls">
		{{ form.description }}
	</div>
</div>

<div class="control-group input-append date">
	<label class="control-label">Startdatum</label>
	<div class="controls input-append date date_select_field" id="dp3" data-date="" data-date-format="yyyy-mm-dd">
		{{ form.start_date }}
		<span class="add-on">
			<i class="icon-calendar"></i>
		</span>
	</div>
</div>

<br/>

<div class="control-group input-append date">
	<label class="control-label">Slutdatum</label>
	<div class="controls input-append date date_select_field" id="dp3" data-date="" data-date-format="yyyy-mm-dd">
		{{ form.end_date }}
		<span class="add-on"><i class="icon-calendar"></i></span>
	</div>
</div>

<div class="control-group">
	<label class="control-label">Medlemmar</label>
	<div class="controls">
		{{ form.members }}
	</div>
</div>

<div class="actions control-group">
	<div class="controls">
		<input type="submit" value="Skapa projekt" class="btn btn-large btn-primary">
	</div>
</div>

Django/Webbramverk/AMPTA/templates/shared/projects_navbar.html
<div class="span3">
	<div class="well sidebar-nav">
		<ul class="nav nav-list">
			<li class="nav-header">Dina projekt</li>
			{% for project in user.projects.all %}
				<li>
					<a href="{% url 'AMPTA:show_project' project.id %}">{{ project.name }}</a>
					{% if project.owner_id == user.id %}
						<span class="label label-success">
							Admin
						</span>
					{% else %}
						<span class="label">
							Medlem
						</span>
					{% endif %}
				</li>
			{% endfor %}
			<li class="nav-header">Dina senaste 10 tickets</li>
			{% for ticket in user.tickets.all %}
				<li>
					<a href="{% url 'AMPTA:show_ticket' ticket.project.id ticket.id %}">
						{{ ticket.name }}
					</a>
				</li>
			{% endfor %}
		</ul>
	</div>
</div>

Django/Webbramverk/AMPTA/templates/shared/ticket_form.html
<input type="hidden" value="{{ project.id }}" name="project_id">
<div class="control-group">
	<label class="control-label">
		Namn
	</label>
	<div class="controls">
		{{ form.name }}
	</div>
</div>

<div class="control-group">
	<label class="control-label">
		Beskrivning
	</label>
	<div class="controls">
		{{ form.description }}
	</div>
</div>

<div class="control-group">
	<label class="control-label">
		Status
	</label>
	<div class="controls">
		{{ form.status }}
	</div>
</div>

<div class="action">
	<input type="submit" value="Spara ticket" class="btn btn-large btn-primary">
</div>

Django/Webbramverk/AMPTA/templates/shared/user_form.html
<div class="control-group">
	<label class="control-label">Namn</label>
	<div class="controls">
		{{ form.first_name }}
		{{ form.last_name }}
	</div>
</div>

<div class="control-group">
	<label class="control-label">Epost</label>
	<div class="controls">
		{{ form.email }}
	</div>
</div>

<div class="actions control-group">
	<div class="controls">
		<input type="submit" value="Spara ändringar" class="btn btn-large btn-primary">
	</div>
</div>