Django/Webbramverk/AMPTA/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.models import User, Group
from django.views.generic import DetailView, ListView
from AMPTA.models import Project, Ticket, Status

from AMPTA import views

urlpatterns = patterns("", 
	url(r'^$', views.index, name = "index"),
	url(r'^login', views.login_user, name = "login"),
	url(r'^logout$', views.logout_user, name = "logout"),
	# project
	url(r'^projects/$', views.projects, name = "projects" ),
	url(r'^projects/(?P<project_id>\d+)$', views.show_project, name = "show_project" ),
	url(r'^projects/(?P<project_id>\d+)/edit$', views.edit_project, name = "edit_project" ),
	url(r'^projects/new$', views.new_project, name = "new_project" ),
	url(r'^projects/create$', views.create_project, name = "create_project" ),
	url(r'^projects/(?P<project_id>\d+)/delete$', views.delete_project, name = "delete_project" ),
	# ticket
	url(r'^projects/(?P<project_id>\d+)/tickets/(?P<ticket_id>\d+)$', views.show_ticket, name = "show_ticket" ),
	url(r'^projects/(?P<project_id>\d+)/tickets/(?P<ticket_id>\d+)/edit$', views.edit_ticket, name = "edit_ticket" ),
	url(r'^projects/(?P<project_id>\d+)/tickets/new$', views.new_ticket, name = "new_ticket" ),
	url(r'^projects/(?P<project_id>\d+)/tickets/create$', views.create_ticket, name = "create_ticket" ),
	url(r'^projects/(?P<project_id>\d+)/tickets/(?P<ticket_id>\d+)/delete$', views.delete_ticket, name = "delete_ticket" ),
	# user
	url(r'^users/$', views.users, name = "users" ),
	url(r'^users/(?P<user_id>\d+)$', views.show_user, name = "show_user" ),
	url(r'^users/(?P<user_id>\d+)/edit$', views.edit_user, name = "edit_user" ),
)

Django/Webbramverk/Webbramverk/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
# from AMPTA.models import Project, Ticket, Status
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Webbramverk.views.home', name='home'),
    # url(r'^Webbramverk/', include('Webbramverk.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^ampta/admin/', include(admin.site.urls)),
    url(r'^ampta/', include("AMPTA.urls", namespace = "AMPTA")),
)

Django/Webbramverk/AMPTA/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User, Group
from django.core.exceptions import ValidationError
from django.utils import timezone
import datetime
from django.forms import ModelForm, Widget
from django import forms

# Create your models here.
class Project(models.Model):
	"""docstring for Project"""
	members = models.ManyToManyField(User, related_name = "projects", error_messages = { "required": "hello" })
	name = models.CharField(max_length = 50, blank = False)
	description = models.TextField(blank = False)
	start_date = models.DateTimeField("Startdatum för projektet")
	end_date = models.DateTimeField("Slutdatum för projektet")
	owner = models.ForeignKey(User, related_name = "owner")
	def __unicode__(self):
		return self.name
	def is_member(self, user):
		return self.members.filter(pk = user.id)
	def valid_deadline(self):
		return self.start_date < self.end_date

class Status(models.Model):
	"""docstring for Status"""
	status_name = models.CharField(max_length = 50, blank = False)
	def __unicode__(self):
		return self.status_name

class Ticket(models.Model):
	"""docstring for Ticket"""
	name = models.CharField(max_length = 50, blank = False)
	description = models.TextField(blank = False)
	project = models.ForeignKey(Project)
	status = models.ForeignKey(Status)
	owner = models.ForeignKey(User, related_name = "tickets")
	def __unicode__(self):
		return self.name

class LoginForm(forms.Form):
	"""docstring for LoginForm"""
	username = forms.CharField(max_length = 30, widget = forms.TextInput(attrs = { "class": "input-block-level" }))
	password = forms.CharField(max_length = 30, widget = forms.PasswordInput(attrs = { "class": "input-block-level" }))

class TicketForm(ModelForm):
	"""docstring for ClassName"""
	class Meta:
		model = Ticket
		exclude = ("project"), ("owner")

class ProjectForm(ModelForm):
	"""docstring for ProjectForm"""
	name = forms.CharField(widget = forms.TextInput(attrs = { "class": "input-xlarge" }))
	description = forms.CharField(widget = forms.Textarea(attrs = { "class": "input-xlarge" }))
	start_date = forms.DateField(initial = timezone.now(), widget = forms.DateInput(attrs = { "class": "span12", "readonly": "" }))
	end_date = forms.DateField(initial = timezone.now() + datetime.timedelta(days = 5), widget = forms.DateInput(attrs = { "class": "span12", "readonly": "" }))
	class Meta:
		model = Project
		exclude = ("owner")
	def clean(self):
		cleaned_data = super(ProjectForm, self).clean()
		start_date = cleaned_data["start_date"]
		end_date = cleaned_data["end_date"]
		if start_date > end_date:
			raise forms.ValidationError("Datum för deadline måste ligga efter startdatum")
		return cleaned_data

class UserForm(ModelForm):
	first_name = forms.CharField(widget = forms.TextInput(attrs = { "class": "input-xlarge", "placeholder": "Förnamn" }))
	last_name = forms.CharField(widget = forms.TextInput(attrs = { "class": "input-xlarge", "placeholder": "Efternamn" }))
	email = forms.EmailField(widget = forms.TextInput(attrs = { "class": "input-xlarge", "placeholder": "Epost" }))
	class Meta:
		model = User
		exclude = ("id"), ("password"), ("last_login"), ("is_superuser"), ("username"), ("is_staff"), ("is_active"), ("date_joined")
			
		














		

Django/Webbramverk/AMPTA/views.py
# -*- coding: utf-8 -*-

# Create your views here.
from django.shortcuts import get_list_or_404, get_object_or_404, render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User, Group

from django.contrib.auth.decorators import login_required, permission_required

from django import template
from django.http import HttpResponse
from django.template import Context, loader
from django.forms import forms

from django.core.urlresolvers import reverse

from AMPTA.models import Project, Ticket, Status, LoginForm, TicketForm, ProjectForm, UserForm

@login_required
def index(request):
	page = "index"
	context = { "page": page }
	return render(request, "index.html", context)

def login_user(request):
	if request.user.is_authenticated():
		return redirect("AMPTA:index")
	message = ""

	if request.method == "POST":
		form = LoginForm(request.POST)
		if form.is_valid():
			username_to_try = form.cleaned_data["username"]
			password_to_try = form.cleaned_data["password"]

			user = authenticate(username = username_to_try, password = password_to_try)
			if user is not None:
				if user.is_active:
					login(request, user)
					return redirect("AMPTA:index")
				else:
					return HttpResponse("<h1>Konto inaktiverat</h1>")	
			else:
				message = "Fel användarnamn eller lösenord"
	else:
		form = LoginForm()
	return render(request, "login/index.html", { "form": form, "message": message })

@login_required
def logout_user(request):
	logout(request)
	return redirect("AMPTA:login")

@login_required
def projects(request):
	projects = get_list_or_404(Project)
	page = "projects"
	context = { "projects": projects, "page": page }
	return render(request, "projects/index.html", context)

@login_required
def show_project(request, project_id):
	project = get_object_or_404(Project, pk = project_id)
	tickets = Ticket.objects.filter(project = project)
	page = "projects"
	context = { "project": project, "tickets": tickets, "page": page }
	return render(request, "projects/show.html", context)

@login_required
def edit_project(request, project_id):
	project = get_object_or_404(Project, pk = project_id)
	page = "projects"
	if request.user.id is not project.owner.id:
		return redirect("AMPTA:show_project", str(project_id))
	if request.method == "POST":
		form = ProjectForm(request.POST, instance = project)
		if form.is_valid():
			project = form.save(commit = False)
			if request.user not in project.members.all():
				project.members.add(request.user)
			project.save()
			context = { "project": project }
			return redirect("AMPTA:show_project", str(project_id))
		else:
			message = "Felaktig formulärdata"
			return render(request, "projects/edit.html", { "project": project, "form": form, "message": message, "page": page })
	if project is not None:
		form = ProjectForm(instance = project)
		context = { "project": project, "form": form }
		return render(request, "projects/edit.html", context)
	else:
		return render(request, "index.html")

@login_required
def new_project(request):
	form = ProjectForm()
	page = "new_project"
	context = { "form": form, "page": page }
	return render(request, "projects/new.html", context)

@login_required
def create_project(request):
	page = "new_project"
	if request.method == "POST":
		form = ProjectForm(request.POST)
		if form.is_valid():
			form.instance.owner = request.user
			project = form.save();
			context = { "project_id": project.id }
			return redirect("AMPTA:show_project", str(project.id))
		else:
			message = "Felaktig formulärdata"
			return render(request, "projects/new.html", { "form": form, "message": message, "page": page })
	else:
		return redirect("AMPTA:new_project")

@login_required
def delete_project(request, project_id):
	project = get_object_or_404(Project, pk = project_id)
	if project is not None:
		if request.user.id == project.owner.id:
			project.delete();
		else:
			pass
	return redirect("AMPTA:index")

@login_required
def show_ticket(request, project_id, ticket_id):
	ticket = get_object_or_404(Ticket, pk = ticket_id)
	page = "projects"
	context = { "ticket": ticket, "page": page }
	return render(request, "tickets/show.html", context)

@login_required
def edit_ticket(request, project_id, ticket_id):
	ticket = get_object_or_404(Ticket, pk = ticket_id)
	project = get_object_or_404(Project, pk = project_id)
	page = "projects"
	if request.user.id is not project.owner.id:
		if request.user.id is not ticket.owner.id:
			return redirect("AMPTA:show_ticket", str(project_id), str(ticket_id))

	if request.method == "POST":
		form = TicketForm(request.POST, instance = ticket)
		if form.is_valid():
			ticket = form.save()
			context = { "project_id": project_id, "ticket": ticket }
			return redirect("AMPTA:show_ticket", str(project_id), str(ticket_id))
		else:
			message = "Felaktig formulärdata"
			return render(request, "tickets/edit.html", { "project": project, "ticket": ticket , "form": form, "message": message, "page": page })
	if ticket is not None and project is not None:
		form = TicketForm(instance = ticket)
		context = { "project": project, "ticket": ticket, "form": form, "page": page }
		return render(request, "tickets/edit.html", context)
	elif project is not None:
		return render(request, "project/show.html", { "project": project, "page": page })
	else:
		return render(request, "index.html", { "page": page })

@login_required
def new_ticket(request, project_id):
	project = get_object_or_404(Project, pk = project_id)
	page = "projects"
	if request.user in project.members.all():
		form = TicketForm()
		context = { "project": project, "form": form, "page": page }
		return render(request, "tickets/new.html", context)
	else:
		return redirect("AMPTA:show_project", str(project_id))

@login_required
def create_ticket(request, project_id):
	project = get_object_or_404(Project, pk = project_id)
	page = "projects"
	if request.user not in project.members.all():
		return redirect("AMPTA:show_project", str(project_id))
	if request.method == "POST":
		form = TicketForm(request.POST)
		if form.is_valid():
			form.instance.owner = request.user
			form.instance.project = project
			ticket = form.save();
			context = { "project_id": project.id, "ticket": ticket }
			return redirect("AMPTA:show_ticket", str(project_id), str(ticket.id))
		else:
			message = "Felaktig formulärdata"
			return render(request, "tickets/new.html", { "project": project, "form": form, "message": message, "page": page })
	else:
		form = TicketForm()
		context = { "project": project, "form": form, "page": page }
		return render(request, "tickets/new.html", context)

@login_required
def delete_ticket(request, project_id, ticket_id):
	project = get_object_or_404(Project, pk = project_id)
	ticket = get_object_or_404(Ticket, pk = ticket_id)
	if request.user.id is not project.owner.id:
		if request.user.id is not ticket.owner.id:
			return redirect("AMPTA:show_ticket", str(project_id), str(ticket_id))

	if project is not None:
		if ticket is not None:
			if request.user.id == ticket.owner.id:
				ticket.delete();
			elif request.user.id == project.owner.id:
				ticket.delete();
			else:
				pass
	return redirect("AMPTA:show_project", str(project_id))

@login_required
def users(request):
	inspect_users = get_list_or_404(User);
	context = { "inspect_users": inspect_users }
	return render(request, "user/index.html", context)

@login_required
def show_user(request, user_id):
	inspect_user = User.objects.get(pk = user_id)
	context = { "inspect_user": inspect_user }
	return render(request, "user/show.html", context)

@login_required
def edit_user(request, user_id):
	inspect_user = get_object_or_404(User, pk = user_id)
	
	if request.user.id is not inspect_user.id:
		if request.user.is_superuser is not True:
			return redirect("AMPTA:index")

	if inspect_user is not None:
		if request.method == "POST":
			form = UserForm(request.POST, instance = inspect_user)
			if form.is_valid():
				inspect_user = form.save()
				context = { "inspect_user": inspect_user }
				return redirect("AMPTA:show_user", str(inspect_user.id))
			else:
				message = "Felaktig formulärdata"
				return render(request, "user/edit.html", { "inspect_user": inspect_user, "form": form })
		else:
			form = UserForm(instance = inspect_user)
			context = { "inspect_user": inspect_user, "form": form }
			return render(request, "user/edit.html", context)
	else:
		return redirect("AMPTA:index")

Django/Webbramverk/AMPTA/templates/projects/edit.html
{% extends "shared/base.html" %}

{% block main_content %}
	<div class="row-fluid">
		{% include "shared/projects_navbar.html" %}
		<div class="span9">
			<div class="hero-unit">
				<h2>Redigera projekt: <i>{{ project.name }}</i></h2>
				<p>
					{% include "shared/error_messages.html" %}
					<form action="{% url 'AMPTA:edit_project' project.id %}" method="post" class="form-horizontal project_form">
						{% csrf_token %}
						{% include "shared/project_form.html" %}
					</form>
				</p>
			</div>
		</div>
	</div>

{% endblock %}

Django/Webbramverk/AMPTA/templates/projects/index.html
{% extends "shared/base.html" %}

{% block main_content %}
	<div class="row-fluid">
		{% include "shared/projects_navbar.html" %}
		<div class="span9">
			<div class="hero-unit">
				<h1>Alla projekt i systemet</h1>
				{% if projects %}
					{% for project in projects %}
						<div>
							{% if user in project.members.all %}
								<span class="label label-success">
									Medlem
								</span>
							{% else %}
								<span class="label label-important">
									Ej medlem
								</span>
							{% endif %}
							<span>
								<a href="{% url 'AMPTA:show_project' project.id %}">{{ project.name }}</a>
							</span>
						</div>
					{% endfor %}
				{% endif %}
			</div>
		</div>
	</div>
{% endblock %}

Django/Webbramverk/AMPTA/templates/projects/new.html
{% extends "shared/base.html" %}

{% block main_content %}
	<div class="row-fluid">
		{% include "shared/projects_navbar.html" %}
		<div class="span9">
			<div class="hero-unit">
				<h1>Skapa ett nytt projekt</h1>
				<p>
					{% include "shared/error_messages.html" %}
					<form action="{% url 'AMPTA:create_project' %}" method="post" class="form-horizontal project_form">
						{% csrf_token %}
						{% include "shared/project_form.html" %}
					</form>
				</p>
			</div>
		</div>
	</div>

{% endblock %}

Django/Webbramverk/AMPTA/templates/projects/show.html
{% extends "shared/base.html" %}

{% block main_content %}
	<div class="row-fluid">
		{% include "shared/projects_navbar.html" %}
		<div class="span9">
			<div class="alert alert-info">
				{% if user in project.members.all %}
					{% if user.id == project.owner_id %}
						<strong>Du har fulla rättigheter till detta projekt</strong>
					{% else %}
						<strong>Du kan lägga till tickets i detta projekt</strong>
					{% endif %}
				{% else %}
					<strong>Du har inga rättigheter i detta projekt</strong>
				{% endif %}
			</div>
			<div class="hero-unit">
				<h2>{{ project.name }}</h2>
				<p>
					<strong>Startdatum: </strong>{{ project.start_date }}
				</p>
				<p>
					<strong>Slutdatum: </strong>{{project.end_date }}
				</p>
				<p>
					<strong>Användare: </strong> <br/>
					{% for u in project.members.all %}
						{{ u.username }}
						<br/>
					{% endfor%}
				</p>

				<p>
					<strong>Tickets: </strong> <br/>
					{% for ticket in tickets.all %}
						<div class="ticket">
							<a href="{% url 'AMPTA:show_ticket' ticket.project.id ticket.id %}">
								{{ ticket.name }}
							</a>
							{% if ticket.status_id == 1 %}
								<span class="label label-important">
									{{ ticket.status.status_name }}
								</span>
							{% elif ticket.status_id == 2 %}
								<span class="label label-warning">
									{{ ticket.status.status_name }}
								</span>
							{% endif %}

							{% if ticket.owner_id == user.id %}
								<span class="label label-success">Ägare</span>
							{% endif %}
						</div>
					{% endfor %}
					<br/>
					{% if user in project.members.all %}
						{% if user.id == project.owner_id %}
							<a href="{% url 'AMPTA:edit_project' project.id %}" class="btn btn-primary">
								Redigera
							</a>
							<a href="{% url 'AMPTA:delete_project' project.id %}" class="btn btn-danger">
								Ta bort projektet
							</a>
							<a href="{% url 'AMPTA:new_ticket' project.id %}" class="btn btn-primary">
								Lägg till ny ticket
							</a>
						{% else %}
							<a href="{% url 'AMPTA:new_ticket' project.id %}" class="btn btn-primary">
								Lägg till ny ticket
							</a>
						{% endif %}
					{% endif %}
				</p>
			</div>
		</div>
	</div>
{% endblock %}