ampta/config/routes.rb
Ampta::Application.routes.draw do

  get "tickets/index"

  
  
  post "tickets" => "ticket#create", :as => "tickets"
  delete "tickets/:id" => "ticket#destroy"
  put "tickets/:id" => "ticket#update"

  get "projects/:id/tickets/:id/edit" => "ticket#edit"
  get "projects/:id/tickets/new" => "ticket#new"
  get "projects/:id/tickets/:id" => "ticket#show", :as => "ticket/show"

  get "logout" => "sessions#destroy", :as => "logout"
  get "start" => "home#index", :as => "start"

  get "projects/new" => "projects#new", :as => "projects/new"
  

  resources :sessions
  resources :projects
  resources :users

  root :to => 'sessions#new'

  resources :projects do
    resources :tickets
      post 'create'
  end

end

ampta/app/models/project.rb
#!/bin/env ruby
# encoding: utf-8
class Project < ActiveRecord::Base
  attr_accessible :name, :description, :start_date, :end_date, :owner_id

  has_many :tickets, :dependent => :destroy
  has_and_belongs_to_many :users

  # validates_presence_of :name
  # validates_presence_of :description
  
  # validates :name, :presence => true,
  #					:length => { :minimum => 5}
  # validates :description, :presence => true,
  #							:length => { :minimum => 5}
  
  # validates :name, :presence => true, :length => { :minimum => 5 }
  validates :name, presence: { :message => "Ett namn måste anges"}, :length => { :minimum => 5 }

  validates :description, :presence => true
end

ampta/app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :status_name

  has_many :tickets
end

ampta/app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :description, :name, :status_id, :user_id, :project_id

  validates :description, :presence => true
  validates :name, :presence => true

  belongs_to :project
  belongs_to :user
  belongs_to :status
  
end

ampta/app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :email, :first_name, :last_name, :password, :password_confirmation
	
	has_many :tickets
	has_and_belongs_to_many :projects

	has_secure_password

	validates_presence_of :email
	validates_uniqueness_of :email

	validates_presence_of :password, :on => :create
	validates_presence_of :password_confirmation, :on => :create

	def self.authenticate(password)
		find_by_email(email).try(:authenticate, password)
	end
end

ampta/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :current_user

private
	def current_user
		@user ||= User.find(session[:user_id]) if session[:user_id]
	end
	helper_method :current_user

	def auth
		if current_user == nil
			redirect_to root_url
		end
	end
end

ampta/app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_filter :auth
	def index
		
	end
end

ampta/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_filter :auth
	def index
		@projects = Project.all
	end

	def show
		@project = Project.find(params[:id])
		session[:session_project_id] = @project.id
	end

	def new
		if session[:failed_project] != nil && session[:failed_validation] != nil
			session[:failed_validation] = nil
			@project = session[:failed_project]
		else
			@project = Project.new
		end
		@users = User.all
	end

	def create
		@project = Project.new(params[:project])
		@project.owner_id = @user.id
		if @project.save
			respond_to do |format|
				unless params[:project_users] == nil
					updateProjectUsers
				end
				@project.users << @user
				session[:failed_project] = nil
				format.html { redirect_to @project, notice: "Projektet skapades" }
			end
		else
			session[:failed_project] = @project
			session[:failed_validation] = "failed_validation"
			redirect_to projects_new_path
		end
	end

	def edit
		@project = Project.find(params[:id])
		if @user.id != @project.owner_id
			redirect_to project_path
		end
		if session[:failed_validation_update_errors] != nil
			@session_errors = session[:failed_validation_update_errors]
			session[:failed_validation_update_errors] = nil
		end

		@users = User.all
	end

	def update
		@project = Project.find(params[:id])
		@project.users.delete(@project.users)
		@project.owner_id = @user.id

		if @project.update_attributes(params[:project])
			unless params[:project_users] == nil
				updateProjectUsers
			end
			@project.users << @user
			session[:failed_project] = nil
			redirect_to @project, notice: "Projektet uppdaterades"
		else
			session[:failed_validation_update_errors] = @project.errors.full_messages
			@project.users << @user
			redirect_to edit_project_path
		end
	end

	def updateProjectUsers
		@project.users.delete(@project.users)
		params[:project_users].each do |u|
			user = User.find(u)
			unless @project.users.include?(user)
				@project.users << user
			end
		end
	end

	def destroy
		@project = Project.find(params[:id])
		@project.destroy
		redirect_to projects_path
	end
end

ampta/app/controllers/sessions_controller.rb
#!/bin/env ruby
# encoding: utf-8
class SessionsController < ApplicationController
  def new
    if session[:user_id]
      redirect_to start_path
    end
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to start_path, :notice => "Inloggad"
  	else
  		flash.now[:error] = "Fel email eller lösenord"
  		render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
    flash[:success] = "Utloggad"
  	redirect_to root_url, :success => "Utloggad" 
  end
end

ampta/app/controllers/ticket_controller.rb
class TicketController < ApplicationController
  before_filter :auth
  def index
  end

  def edit
  	@ticket = Ticket.find(params[:id])
    @project = @ticket.project
    if @user.id != @ticket.user_id && @user.id != @ticket.project.owner_id
      redirect_to project_path(@project)
    end
  	if session[:failed_ticket_validation_update_errors] != nil
  		@session_update_errors = session[:failed_ticket_validation_update_errors]
  		session[:failed_ticket_validation_update_errors] = nil
  	end
  end

  def update
  	@ticket = Ticket.find(params[:id])
    @project = @ticket.project

  	if @ticket.update_attributes(params[:ticket])
  		redirect_to project_path(session[:session_project_id]) + ticket_path(@ticket)
  	else
  		session[:failed_ticket_validation_update_errors] = @ticket.errors.full_messages
  		redirect_to project_path(session[:session_project_id]) + edit_ticket_path
  	end
  end

  def new
    if @user.projects.include?(session[:session_project_id])
      # redirect_to project_path
    end
  	if session[:failed_ticket] != nil && session[:failed_ticket_validation] != nil
  		session[:failed_ticket_validation] != nil
  		@ticket = session[:failed_ticket]
  	else 
  		@ticket = Ticket.new
  	end
  end

  def create
  	@ticket = Ticket.new(params[:ticket])
  	@ticket.user_id = @user.id
  	@ticket.project_id = session[:session_project_id]
    
  	if @ticket.save
  		#redirect_to Project.find(session[:session_project_id])
  		session[:failed_ticket] = nil
  		redirect_to project_path(session[:session_project_id])
  	else
  		session[:failed_ticket] = @ticket
  		session[:failed_ticket_validation] = "failed_ticket_validation"
  		render :action => "new"
  	end
  end

  def show
  	@ticket = Ticket.find(params[:id])
    @project = @ticket.project
  end

  def destroy
    if @user.id != @ticket.user_id && @user.id != @ticket.project.owner_id
      redirect_to project_path(@project)
    end
  	@ticket = Ticket.find(params[:id])
  	@ticket.destroy
  	redirect_to project_path(session[:session_project_id])
  end
end

ampta/app/helpers/application_helper.rb
module ApplicationHelper
end

ampta/app/helpers/home_helper.rb
module HomeHelper
end

ampta/app/helpers/projects_helper.rb
module ProjectsHelper
end

ampta/app/helpers/sessions_helper.rb
module SessionsHelper
end

ampta/app/helpers/ticket_helper.rb
module TicketHelper
end

ampta/app/views/home/index.html.erb
<div class="row-fluid">
	<div class="span3">
		<div class="well sidebar-nav">
			<ul class="nav nav-list">
				<li class="nav-header">Dina projekt</li>
				<li>1</li>
				<li>2</li>
				<li>3</li>
				<li class="nav-header">Dina senaste 10 tickets</li>
				<li>4</li>
				<li>5</li>
				<li>6</li>
			</ul>
		</div>
	</div>

	<div class="span9">
		<div class="hero-unit">
			<h2>Välkommen till Project Manager</h2>
			<p>Här kan du välja dina projekt eller tickets</p>
		</div>
	</div>
</div>

ampta/app/views/layouts/_menu.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "AMPTA", start_path, :class => "brand" %>
			<div class="nav-collapse collapse">
				<ul class="nav">
					<li class="<%= 'active' if params[:controller] == 'home' %>">
						<%= link_to "Start", start_path %>
					</li>

					<li class="<%= 'active' if params[:controller] == 'projects' && params[:action] == "index" || params[:controller] == 'projects' && params[:action] == "show" %>">
						<%= link_to "Alla projekt", projects_path %>
					</li>

					<li class="<%= 'active' if params[:controller] == 'projects' && params[:action] == 'new' %>">
						<%= link_to "Skapa projekt", projects_new_path %>
					</li>
				</ul>
				<p class="navbar-text pull-right">
					Inloggad som <%= @user.first_name %> - 
					<%= link_to "Logga ut", logout_path, :action => "destroy" %>
				</p>
			</div>
		</div>
	</div>
</div>

ampta/app/views/layouts/_projects_navbar.html.erb
<div class="span3">
	<div class="well sidebar-nav">
		<ul class="nav nav-list">
			<li class="nav-header">Dina projekt</li>
			<% @user.projects.each do |project| %>
				<li>
					<%= link_to project.name, project %>
					<% if project.owner_id == @user.id %>
						<span class="label label-success">
							Admin
						</span>
					<% else %>
						<span class="label">
							Medlem
						</span>
					<% end %>
				</li>
			<% end %>
			</table>
			<li class="nav-header">Dina senaste 10 tickets</li>
			<% @user.tickets.each do |ticket| %>
				<li>
					<%= link_to ticket.name, project_path(ticket.project.id) + ticket_path(ticket) %>
				</li>
			<% end %>
		</ul>
	</div>
</div>

ampta/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ampta</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= unless @user == nil
		render "layouts/menu"
	end %>
	<div class="container-fluid" id="main_container">
		<%= yield %>
	</div>
</body>
</html>

ampta/app/views/projects/_form.html.erb
<% if @project.errors.any? %>
  <div id="error_explanation" class="alert alert-error">
    <h4><%= @project.errors.count %> fel gjorde att projektet inte kunde sparas</h4>
    <% @project.errors.full_messages.each do |msg| %>
        <span><%= msg %></span><br/>
    <% end %>
  </div>
<% end %>
<%= form_for(@project, :html => { :class => "form-horizontal project_form"} ) do |f| %>
  <!--<%= @project.errors.any? %>-->
  <div class="control-group">
    <%= f.label :name, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :name, :class => "input-xlarge" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => "control-label" %>
    <div class="controls">
      <%= f.text_area :description, :class => "input-xlarge", :rows => "5" %>
    </div>
  </div>
  <div class="control-group date_group">
    <%= f.label :start_date, :class => "control-label" %>
    <div class="controls">
      <%= f.date_select :start_date %>
    </div>
  </div>

  <div class="control-group date_group">
    <%= f.label :end_date, :class => "control-label" %>
    <div class="controls">
      <%= f.date_select :end_date, :html_options => { :class => "input-mini"} %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <% @users.each do |u| %>
        <% if u.id != @user.id %>
          <label class="checkbox">
            <%= check_box_tag "project_users[]", u.id, u.projects.include?(@project) %>
            <%= u.first_name %>
          </label>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="actions control-group">
    <div class="controls">
      <%= f.submit :class => "btn btn-large btn-primary" %>
    </div>
  </div>
<% end %>

ampta/app/views/projects/_form_old.html.erb
<%= form_for(@project, :html => { :class => "form-horizontal"} ) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description %>
    <div class="controls">
      <%= f.text_field :description %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :start_date %>
    <div class="controls">
      <%= f.date_select :start_date %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :end_date %>
    <div class="controls">
      <%= f.date_select :end_date %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ampta/app/views/projects/edit.html.erb
<div class="row-fluid">
	<%= render "layouts/projects_navbar" %>
	<div class="span9">
		<div class="hero-unit">
			<h2>Redigera projekt:
				"<%= @project.name %>"
			</h2>
			<p>
				<% if @session_errors %>
				  <div id="error_explanation" class="alert alert-error">
				    <h4><%= @session_errors.count %> fel gjorde att projektet inte kunde sparas</h4>
				    <% @session_errors.each do |msg| %>
				        <span><%= msg %></span><br/>
				    <% end %>
				  </div>
				<% end %>
				<%= render "form" %>
			</p>
		</div>
	</div>
</div>

ampta/app/views/projects/index.html.erb
<div class="row-fluid">
	<%= render "layouts/projects_navbar" %>
	<div class="span9">
		<div class="hero-unit">
			<h1>Alla projekt i systemet</h1>
			<% @projects.each do |project| %>
				<div>
					<% if project.users.include?(@user) %>
						<span class="label label-success">
							Medlem
						</span>
					<% else %>
						<span class="label label-important">
							Ej medlem
						</span>
					<% end %>
					<span>
						<%= link_to project.name, project %>
					</span>
				</div>
			<% end %>
		</div>
	</div>
</div>

ampta/app/views/projects/new.html.erb
<div class="row-fluid">
	<%= render "layouts/projects_navbar" %>
	<div class="span9">
		<div class="hero-unit">
			<h1>Skapa ett nytt projekt</h1>
			<p>
				<%= render "form" %>
			</p>
		</div>
	</div>
</div>

ampta/app/views/projects/show.html.erb
<div class="row-fluid">
	<%= render "layouts/projects_navbar" %>
	<div class="span9">
		<div class="alert alert-info">
			<% if @project.users.include?(@user) && @project.owner_id == @user.id %>
				<strong>Du har fulla rättigheter till detta projekt</strong>
			<% elsif @project.users.include?(@user) %>
				<strong>Du kan lägga till tickets i detta projekt</strong>
			<% else %>
				<strong>Du har inga rättigheter i detta projekt</strong>
			<% end %>
		</div>
		<div class="hero-unit">
			
			<h2><%= @project.name %></h2>
			<p>
				<strong>Startdatum: </strong><%= @project.start_date%>
			</p>
			<p>
				<strong>Slutdatum: </strong><%= @project.end_date%>
			</p>
			<p>
				<strong>Användare: </strong> <br/>
				<% @project.users.each do |u| %>
					<%= u.first_name %> <br/>
				<% end %>
			</p>
			<p>
				<strong>Tickets: </strong> <br/>
				<% @project.tickets.each do |t| %>
					<div class="ticket">
						<%= link_to t.name, @project.id.to_s + ticket_path(t) %>
						<% if t.status_id == 1 %>
							<span class="label label-important">
								<%= t.status.status_name%>
							</span>
						<% elsif t.status_id == 2 %>
							<span class="label label-warning">
								<%= t.status.status_name%>
							</span>
						<% end %>

						<% if t.user_id == @user.id %>
							<span class="label label-success">Ägare</span>
						<% end %>
					</div>
					
				<% end %>
				<br/>
				<% if @project.users.include?(@user) %>
					<%= link_to "Lägg till ny ticket", project_path(session[:session_project_id]) + new_ticket_path, :class => "btn btn-primary" %>
				<% end %>
			</p>
			<% if @user.id == @project.owner_id %>
				<%= link_to 'Redigera', edit_project_path, :class => "btn btn-primary" %>
				<%= link_to 'Ta bort projektet', @project, method: :delete, data: { confirm: 'Är du säker på att du vill ta bort detta projekt?' }, :class => "btn btn-danger" %>
			<% end %>
		</div>
	</div>
</div>

ampta/app/views/ticket/_form.html.erb
<% if @ticket.errors.any? %>
  <div id="error_explanation" class="alert alert-error">
    <h4><%= @ticket.errors.count %> fel gjorde att ticketen inte kunde sparas</h4>
    <% @ticket.errors.full_messages.each do |msg| %>
        <span><%= msg %></span><br/>
    <% end %>
  </div>
<% end %>
<%= form_for(@ticket, :html => { :class => "form-horizontal ticket_form"} ) do |f| %>
  <!--<%= @ticket.errors.any? %>-->
  <div class="control-group">
    <%= f.label :name, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :name, :class => "input-xlarge" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => "control-label" %>
    <div class="controls">
      <%= f.text_area :description, :class => "input-xlarge", :rows => "5" %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">Status </label>
    <div class="controls">
      <%= f.select :status_id, options_from_collection_for_select(Status.all, :id, :status_name) %>
    </div>
  </div>
  <div class="actions control-group">
    <div class="controls">
      <%= f.submit :class => "btn btn-large btn-primary" %>
    </div>
  </div>
<% end %>

ampta/app/views/ticket/edit.html.erb
<div class="row-fluid">
	<%= render "layouts/projects_navbar" %>
	<div class="span9">
		<div class="hero-unit">
			<h2>Redigera ticket:
				<%= @ticket.name %>
			</h2>
			<p>
				<% if @session_update_errors %>
				  <div id="error_explanation" class="alert alert-error">
				    <h4><%= @session_update_errors.count %> fel gjorde att ticketen inte kunde sparas</h4>
				    <% @session_update_errors.each do |msg| %>
				        <span><%= msg %></span><br/>
				    <% end %>
				  </div>
				<% end %>
				<%= render "form" %>
			</p>
		</div>
	</div>
</div>

ampta/app/views/ticket/index.html.erb
<h1>Ticket#index</h1>
<p>Find me in app/views/ticket/index.html.erb</p>

ampta/app/views/ticket/new.html.erb
<div class="row-fluid">
	<%= render "layouts/projects_navbar" %>
	<div class="span9">
		<div class="hero-unit">
			<h1>Skapa en ny ticket</h1>
			<p>
				<%= render "form" %>
			</p>
		</div>
	</div>
</div>

ampta/app/views/ticket/show.html.erb
<div class="row-fluid">
	<%= render "layouts/projects_navbar" %>
	<div class="span9">
		<div class="hero-unit">
			<h2><%= @ticket.name %></h2>
			<p>
				<strong>Beskrivning: </strong>
				<br/>
				<%= @ticket.description %>
			</p>
			<p>
				<strong>Ägare: </strong>
				<br/>
				<%= @ticket.user.first_name %> <%= @ticket.user.last_name %>
			</p>
			<p>
				<strong>Status: </strong>
				<br/>
				<%= @ticket.status.status_name %>
			</p>
			<p>
				
			</p>
			<% if @user.id == @ticket.user_id || @user.id == @ticket.project.owner_id %>
				<%= link_to 'Redigera ticket', project_path(session[:session_project_id]) + edit_ticket_path, :class => "btn btn-primary" %>
				<%= link_to 'Ta bort ticket', ticket_path(@ticket), method: :delete, data: { confirm: 'Är du säker på att du vill ta bort denna ticket?' }, :class => "btn btn-danger" %>
			<% end %>
			<p>
				<%= link_to "Tillbaka", project_path(@project.id) %>
			</p>
		</div>
	</div>
</div>